name: API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      LOGISTICIAN_SAAS_USERNAME: ${{ secrets.LOGISTICIAN_SAAS_USERNAME }}
      LOGISTICIAN_SAAS_PASSWORD: ${{ secrets.LOGISTICIAN_SAAS_PASSWORD }}
      LOGISTICIAN_IIKO_USERNAME: ${{ secrets.LOGISTICIAN_IIKO_USERNAME }}
      LOGISTICIAN_IIKO_PASSWORD: ${{ secrets.LOGISTICIAN_IIKO_PASSWORD }}
      COURIER_SAAS_PHONE: ${{ secrets.COURIER_SAAS_PHONE }}
      COURIER_SAAS_CODE: ${{ secrets.COURIER_SAAS_CODE }}
      COURIER_SAAS_ID: ${{ secrets.COURIER_SAAS_ID }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -s -v -k test_any_order_delivery --alluredir=allure-results

      - name: Prepare Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report